#!/usr/bin/env bash

source NTR/GameTweakz
# Banner Add
echo -e "executing: ${LIGHTGREEN}GameTweakz ❤️ NTR ENHANCED ${NOCOLOR}"
echo "-----------------------"

if [[ -d "Dump-Maal" ]]
  then
    echo ""
  else
    echo ""
    mkdir Dump-Maal
fi

unpack-filesing () {
  qemu-i386 $PREFIX/share/quickbms/quickbms -Q etc/NTR.bms $opt Dump-Maal
}

repack-filesing () {
  qemu-i386 $PREFIX/share/quickbms/quickbms -w -r -r etc/NTR.bms $opt Dump-Maal
}

function unpack-files {
prompt="Please select a file to unpack-files:"
options=( $(find *.pak) )

PS3="$prompt "
select opt in "${options[@]}" "Quit" ; do 
    if (( REPLY == 1 + ${#options[@]} )) ; then
        exit

    elif (( REPLY > 0 && REPLY <= ${#options[@]} )) ; then
        echo  "You picked $opt which is file $REPLY"
         unpack-filesing
        break

    else
        echo "Invalid option. Try another one."
    fi
done
}

function repack-files {
prompt="Please select a file to repack-files:"
options=( $(find *.pak) )

PS3="$prompt "
select opt in "${options[@]}" "Quit" ; do 
    if (( REPLY == 1 + ${#options[@]} )) ; then
        exit

    elif (( REPLY > 0 && REPLY <= ${#options[@]} )) ; then
        echo  "You picked $opt which is file $REPLY"
         repack-filesing
        break
    else
        echo "Invalid option. Try another one."
    fi
done
}

PS3='Please enter your choice: '
options=("Unpack-files" "Repack-files" "Quit")
select opt in "${options[@]}"
do
    case $opt in
        "Unpack-files")
            unpack-files
            break
            ;;
        "Repack-files")
            repack-files
            
            ;;
        "Quit")
            break
            ;;
        *) echo "invalid option $REPLY";;
    esac
done 
